name: Build SSG and deploy

on:
  push:
    branches:
      - main


jobs:
  pocketbase:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kevinganthy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kevinganthy/pocketcv:latest

  build:
    runs-on: ubuntu-latest
    needs: pocketbase
    
    services:
      pocketbase:
        image: kevinganthy/pocketcv:latest
        ports:
          - 8090:8090
        options: >-
          --health-cmd="curl -f http://localhost:8090/api/health || exit 1"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=10
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Wait for PocketBase
        run: |
          until curl -s http://localhost:8090/api/health; do
            echo "Waiting for PocketBase..."
            sleep 5
          done

      - name: Build Frontend
        run: |
          cd front
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: front/out
          compression-level: 1
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5