---
name: DockerHub

on:
  push:
    branches:
      - main
    paths:
      - 'pocketbase/**'

jobs:
  pocketbase:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kevinganthy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('pocketbase/**/*') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./pocketbase/
          push: true
          tags: kevinganthy/pocketcv:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max


